AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  StockPrices:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Stock_Prices
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::435179308234:role/StocksLambda'
      Runtime: python3.6
      Timeout: 600
